### PR TITLE
Bug Fixes and Additions to Bernstein

### PR DESCRIPTION
**Pull request by rdebrand**
Includes your restructuring of parametrizations and fixes one export bug in bernstein.jl and adds to fit.jl
I squashed your commits on a local clone, thats why they are not shown (hope it's not a problem)

### CODE REVIEW

**Comment by rdebrand** [comment]
Some is renaming (Bernstein_fit.jl, Bernstein_forward_model.jl, PartonDensity.jl's changed includes) and some is rewriting of the functions to take a Union (Bernstein_forward_model.jl, forward_model.jl) and bernstein.jl has got an added necessary export.

**Comment by cescalara** [comment]
OK, you are welcome to handle the conflicts, but I can have a look later if there is some confusion. Let me know!

**Comment by rdebrand** [comment]
I think this should have resolved the conflicts, maybe look through the changes, if they are ok.

**Comment by rdebrand** [comment]
Oh yes, you're right, I forgot to change that include. Should be working now!

**Review by cescalara — APPROVED** [review]
Looks good! Thank you for taking care of the conflicts and getting this working.

**Pull request merged**
