### PR TITLE
Add CQDNUM to deps

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by oschulz** [comment]
I'll fix those test failures.

**Comment by cescalara** [comment]
I think it is perhaps just that QCDNUM.jl still needs to be loaded from main as I've been making changes there...

**Comment by oschulz** [comment]
Can you trigger CI again now?

**Comment by oschulz** [comment]
Could you make a new QCDNUM release?

**Comment by cescalara** [comment]
I have a list of further changes I wanted to make first - is it urgent?

**Comment by oschulz** [comment]
> is it urgent

No, maybe best to make those changes first.

**Comment by cescalara** [comment]
I'll get to it soon!

**Pull request merged**
